import { Notice, Plugin } from 'obsidian';
import { QuarterlyReviewSettings } from '../settings';

export async function buildQuarterlyReview(plugin: Plugin & { settings: QuarterlyReviewSettings }) {
	try {
		const { tempFolderPath } = plugin.settings;

		// Get current date to determine quarter
		const now = new Date();
		const year = now.getFullYear();
		const month = now.getMonth() + 1; // getMonth() returns 0-11
		const quarter = Math.ceil(month / 3);

		// Create quarterly review content
		const quarterlyReviewContent = `# Quarterly Review - Q${quarter} ${year}

## Quarter Overview
**Period:** Q${quarter} ${year}
**Generated:** ${now.toLocaleDateString()}

## Goals & Objectives
- [ ] Goal 1
- [ ] Goal 2
- [ ] Goal 3

## Key Achievements
- Achievement 1
- Achievement 2
- Achievement 3

## Challenges & Lessons Learned
### Challenges
- Challenge 1
- Challenge 2

### Lessons Learned
- Lesson 1
- Lesson 2

## Metrics & KPIs
| Metric | Target | Actual | Status |
|--------|--------|--------|--------|
| Metric 1 | | | |
| Metric 2 | | | |
| Metric 3 | | | |

## Next Quarter Planning
### Priorities for Q${quarter === 4 ? 1 : quarter + 1} ${quarter === 4 ? year + 1 : year}
- [ ] Priority 1
- [ ] Priority 2
- [ ] Priority 3

### Action Items
- [ ] Action item 1
- [ ] Action item 2
- [ ] Action item 3

## Notes
*Add any additional notes or reflections here*

---
*Generated by Quarterly Review Builder plugin*
*Temp folder: ${tempFolderPath}*
`;

		// Ensure temp folder exists
		const tempFolder = plugin.app.vault.getAbstractFileByPath(tempFolderPath);
		if (!tempFolder) {
			await plugin.app.vault.createFolder(tempFolderPath);
		}

		// Create the quarterly review file
		const fileName = `Q${quarter}_${year}_Review.md`;
		const filePath = `${tempFolderPath}/${fileName}`;

		// Check if file already exists
		const existingFile = plugin.app.vault.getAbstractFileByPath(filePath);
		if (existingFile) {
			new Notice(`Quarterly review file already exists: ${fileName}`);
			// Open the existing file
			const file = plugin.app.vault.getFileByPath(filePath);
			if (file) {
				await plugin.app.workspace.getLeaf().openFile(file);
			}
			return;
		}

		// Create the new file
		const newFile = await plugin.app.vault.create(filePath, quarterlyReviewContent);

		// Open the newly created file
		await plugin.app.workspace.getLeaf().openFile(newFile);

		new Notice(`Quarterly review created: ${fileName}`);

	} catch (error) {
		console.error('Error building quarterly review:', error);
		new Notice('Failed to create quarterly review. Check console for details.');
	}
}
